# Generated by Django 4.1.7 on 2023-03-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[(1, 'Dog Owner'), (2, 'Dog Sitter'), (3, 'Dog Walker')], default=1, max_length=2),
        ),
    ]
