# Generated by Django 4.1.7 on 2023-04-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_booking_date_remove_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Quezon City', max_length=50),
        ),
    ]
