# Generated by Django 4.1.7 on 2023-04-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(default='Metro Manila', max_length=50),
        ),
    ]
